site_name: QareBlog
site_url: https://example.com
theme:
  name: material
  language: fa
  palette:
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/weather-night
        name: حالت تاریک
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/weather-sunny
        name: حالت روشن
features:
    - navigation.indexes

plugins:
  - search
  - blog:
      blog_dir: blog
      post_dir: blog/posts
      post_url_format: "{date}/{slug}"
      archive: true
      categories: true
      tags: true

nav:
  - خانه: index.md
  - درباره: about.md
  - تماس: contact.md
  # - وبلاگ: blog/index.md

  # - وبلاگ: blog/index.md


extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/posts-index.js
